window.DINORAMTIX_CONFIG = {
  supabaseUrl: "https://aaoyqpiydwqobbtdmmno.supabase.co",
  supabasePublishableKey: "sb_publishable_5SAEn1z1PEtbGe6mNDjcaA_Kfwz-plG"
};

(function(){
  function linkMentions(root){if(!root||root.nodeType!==1)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];let n;while(n=w.nextNode()){if(n.parentElement&&n.parentElement.closest('button,a,input,textarea,script,style'))continue;if(/(^|\s)@[a-zA-Z0-9_.]{2,30}\b/.test(n.nodeValue))nodes.push(n)}nodes.forEach(node=>{const text=node.nodeValue,frag=document.createDocumentFragment();let last=0,m;const re=/(^|\s)(@[a-zA-Z0-9_.]{2,30})\b/g;while((m=re.exec(text))){if(m.index>last)frag.appendChild(document.createTextNode(text.slice(last,m.index)));if(m[1])frag.appendChild(document.createTextNode(m[1]));const a=document.createElement('a');a.href='#';a.textContent=m[2];a.style.cssText='color:#0095f6;font-weight:700;text-decoration:none;cursor:pointer';const username=m[2].slice(1);a.onclick=async e=>{e.preventDefault();try{const db=window.supabase?.createClient?.(window.DINORAMTIX_CONFIG.supabaseUrl,window.DINORAMTIX_CONFIG.supabasePublishableKey);const r=await db?.from('profiles').select('id').eq('username',username).maybeSingle();if(r?.data?.id&&typeof window.profile==='function')window.profile(r.data.id);else alert('No encontramos a @'+username)}catch(err){alert('No se pudo abrir @'+username)}};frag.appendChild(a);last=re.lastIndex}if(last<text.length)frag.appendChild(document.createTextNode(text.slice(last)));node.parentNode.replaceChild(frag,node)})}
  function start(){linkMentions(document.body);new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(n=>{if(n.nodeType===1)linkMentions(n)}))).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();

(function(){
  const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  let adminDb=null,installed=false;const $=id=>document.getElementById(id);
  async function install(){
    if(installed||!window.supabase)return false;
    adminDb=window.supabase.createClient(DINORAMTIX_CONFIG.supabaseUrl,DINORAMTIX_CONFIG.supabasePublishableKey);
    const {data:{session}}=await adminDb.auth.getSession();if(!session?.user)return false;
    const {data:me,error}=await adminDb.from('profiles').select('id,username,is_admin').eq('id',session.user.id).maybeSingle();
    if(error||!me?.is_admin)return true;
    const tabs=document.querySelector('#app>.tabs');if(!tabs)return false;
    if(!$('adminVerifyTab')){const b=document.createElement('button');b.id='adminVerifyTab';b.className='g';b.textContent='🛡️ Verificar usuarios';b.onclick=openAdmin;tabs.appendChild(b)}
    if(!$('adminVerify')){const sec=document.createElement('section');sec.id='adminVerify';sec.className='hidden';sec.innerHTML='<div class="card"><h2>🛡️ Verificar usuarios</h2><p class="muted">Puedes verificar cualquier cuenta, aunque tenga menos de 10.000 seguidores.</p><input id="verifySearch" placeholder="Buscar usuario..." oninput="loadVerifyUsers()"><div id="verifyUsers"><p class="muted">Cargando usuarios...</p></div><hr><h2>🚫 Administrar baneos</h2><input id="banSearch" placeholder="Buscar usuario..." oninput="loadBanUsers()"><div id="banUsers"></div></div>';document.querySelector('#app').appendChild(sec)}
    installed=true;return true;
  }
  async function loadVerifyUsers(){if(!adminDb||!$('verifyUsers'))return;const q=($('verifySearch')?.value||'').trim();let req=adminDb.from('profiles').select('id,username,avatar_url,followers_count,verified').order('username').limit(100);if(q)req=req.ilike('username','%'+q+'%');const {data,error}=await req;if(error){$('verifyUsers').innerHTML='<p>'+esc(error.message)+'</p>';return}$('verifyUsers').innerHTML=(data||[]).map(u=>`<div class="card row" style="margin:8px 0">${u.avatar_url?`<img src="${esc(u.avatar_url)}" style="width:48px;height:48px;border-radius:50%;object-fit:cover">`:`<div class="avatar">${esc((u.username||'?')[0].toUpperCase())}</div>`}<div class="grow"><b>@${esc(u.username)}</b><div class="muted">${u.followers_count||0} seguidores</div></div><span>${u.verified?'🟦 Verificado':'Sin verificar'}</span><button class="${u.verified?'g':'p'}" onclick="setVerified('${u.id}',${!u.verified})">${u.verified?'Quitar verificado':'✓ Verificar'}</button></div>`).join('')||'<p class="muted">No hay usuarios.</p>'}
  async function setVerified(id,value){if(!adminDb)return;const {error}=await adminDb.rpc('admin_set_verified',{target_user:id,new_value:value});if(error){alert('No se pudo cambiar el verificado: '+error.message);return}await loadVerifyUsers();alert(value?'Usuario verificado 🟦':'Verificado retirado')}
  async function loadBanUsers(){if(!adminDb||!$('banUsers'))return;const q=($('banSearch')?.value||'').trim();let req=adminDb.from('profiles').select('id,username,verified').order('username').limit(100);if(q)req=req.ilike('username','%'+q+'%');const {data,error}=await req;if(error)return $('banUsers').innerHTML='<p>'+esc(error.message)+'</p>';const ids=(data||[]).map(x=>x.id);let bans=[];if(ids.length){const r=await adminDb.from('bans').select('user_id').in('user_id',ids);bans=r.data||[]}const set=new Set(bans.map(x=>x.user_id));$('banUsers').innerHTML=(data||[]).map(u=>`<div class="card row"><div class="grow"><b>@${esc(u.username)}</b></div>${set.has(u.id)?'<span>🚫 Baneado</span><button class="g" onclick="unbanUser(\''+u.id+'\')">Desbanear</button>':'<button class="d" onclick="banUser(\''+u.id+'\')">🚫 Banear</button>'}</div>`).join('')||'<p class="muted">No hay usuarios.</p>'}
  async function banUser(id){const reason=prompt('Motivo del baneo:')??'';const {error}=await adminDb.rpc('admin_ban_user',{target_user:id,reason_text:reason});if(error)return alert(error.message);loadBanUsers();alert('Usuario baneado')}
  async function unbanUser(id){const {error}=await adminDb.rpc('admin_unban_user',{target_user:id});if(error)return alert(error.message);loadBanUsers();alert('Usuario desbaneado')}
  function openAdmin(){['feed','explore','reels','create','me','profile','chat','settings'].forEach(x=>$(x)?.classList.add('hidden'));$('adminVerify')?.classList.remove('hidden');loadVerifyUsers();loadBanUsers()}
  window.loadVerifyUsers=loadVerifyUsers;window.setVerified=setVerified;window.openAdmin=openAdmin;window.loadBanUsers=loadBanUsers;window.banUser=banUser;window.unbanUser=unbanUser;
  let tries=0;const timer=setInterval(async()=>{const ok=await install();if(ok||++tries>40)clearInterval(timer)},500)
})();

/* Funciones sociales adicionales: tema, chat, voz, modal de publicaciones y control de baneos. */
(function(){
  const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
  let db2=null, chatUser=null, recorder=null, voiceChunks=[];
  function init(){
    if(!window.supabase)return;
    db2=window.supabase.createClient(DINORAMTIX_CONFIG.supabaseUrl,DINORAMTIX_CONFIG.supabasePublishableKey);
    const old=window.start;window.start=async function(){const r=old?await old.apply(this,arguments):null;await ensureNotBanned();await addSocialUI();return r};
    const oldGuest=window.guest;window.guest=function(){oldGuest?.();addSocialUI()};
    addSocialUI();
  }
  async function ensureNotBanned(){if(!window.me)return;const r=await db2.from('bans').select('reason').eq('user_id',window.me.id).maybeSingle();if(r.data){document.body.innerHTML='<main style="max-width:600px;margin:80px auto;padding:30px;text-align:center;font-family:Arial"><h1>🚫 Cuenta suspendida</h1><p>Esta cuenta ha sido baneada de DinoRamtix.</p><p>'+esc(r.data.reason||'Sin motivo especificado')+'</p></main>';throw new Error('Banned')}}
  async function addSocialUI(){
    if(!$('app'))return;
    const tabs=document.querySelector('#app>.tabs');if(tabs&&!$('chatTab')){const b=document.createElement('button');b.id='chatTab';b.className='g';b.textContent='💬 Chat';b.onclick=()=>openChat();tabs.appendChild(b)}
    if(tabs&&!$('themeTab')){const b=document.createElement('button');b.id='themeTab';b.className='g';b.textContent='🎨 Color';b.onclick=themePanel;tabs.appendChild(b)}
    if(!$('chat')){const s=document.createElement('section');s.id='chat';s.className='hidden';s.innerHTML='<div class="card"><h2>💬 Chat</h2><input id="chatSearch" placeholder="Buscar usuario..." oninput="searchChatUsers()"><div id="chatUsers"></div><div id="chatBox" class="hidden"><div class="row"><button class="g" onclick="backChat()">←</button><b id="chatTitle"></b></div><div id="messages" style="height:420px;overflow:auto;padding:10px"></div><div class="row"><input id="chatInput" placeholder="Escribe un mensaje..."><button class="p" onclick="sendChat()">Enviar</button><button class="g" onclick="toggleVoice()">🎙️</button></div><div id="voiceStatus" class="muted"></div></div></div>';document.querySelector('#app').appendChild(s)}
    if(!$('themePanel')){const s=document.createElement('section');s.id='themePanel';s.className='hidden';s.innerHTML='<div class="card"><h2>🎨 Personalizar interfaz</h2><p class="muted">Elige el color principal de DinoRamtix.</p><input id="accentPicker" type="color" value="#0095f6" style="width:70px;height:45px"><button class="p" onclick="saveAccent()">Guardar color</button></div>';document.querySelector('#app').appendChild(s)}
    applyAccent();
    document.addEventListener('click',mediaClickHandler,{capture:true});
  }
  async function applyAccent(){if(!db2)return;let r=await db2.from('user_settings').select('accent').eq('user_id',window.me?.id||'').maybeSingle();if(r.data?.accent)document.documentElement.style.setProperty('--accent',r.data.accent);const s=document.createElement('style');s.textContent='.p{background:var(--accent,#0095f6)!important}.mention{color:var(--accent,#0095f6)!important}.verified{background:var(--accent,#168df7)!important}';document.head.appendChild(s);if($('accentPicker')&&r.data?.accent)$('accentPicker').value=r.data.accent}
  async function saveAccent(){if(!window.me)return alert('Inicia sesión');const c=$('accentPicker').value;const r=await db2.rpc('set_my_accent',{new_accent:c});if(r.error)return alert(r.error.message);document.documentElement.style.setProperty('--accent',c);alert('Color guardado 🎨')}
  function themePanel(){['feed','explore','reels','create','me','profile','chat','adminVerify'].forEach(x=>$(x)?.classList.add('hidden'));$('themePanel')?.classList.remove('hidden');applyAccent()}
  async function openChat(){if(!window.me)return alert('Inicia sesión para chatear');['feed','explore','reels','create','me','profile','adminVerify','themePanel'].forEach(x=>$(x)?.classList.add('hidden'));$('chat').classList.remove('hidden');$('chatBox').classList.add('hidden');searchChatUsers()}
  async function searchChatUsers(){if(!db2||!$('chatUsers'))return;const q=($('chatSearch')?.value||'').trim();let req=db2.from('profiles').select('id,username,avatar_url,verified').neq('id',window.me?.id||'').order('username').limit(30);if(q)req=req.ilike('username','%'+q+'%');const r=await req;if(r.error)return $('chatUsers').innerHTML='<p>'+esc(r.error.message)+'</p>';$('chatUsers').innerHTML=(r.data||[]).map(u=>`<button class="g" style="display:block;width:100%;text-align:left;margin:6px 0" onclick="openConversation('${u.id}','${esc(u.username)}')">@${esc(u.username)}${u.verified?' 🟦':''}</button>`).join('')||'<p class="muted">No hay usuarios.</p>'}
  async function openConversation(uid,name){chatUser=uid;$('chatTitle').textContent='@'+name;$('chatUsers').innerHTML='';$('chatBox').classList.remove('hidden');await loadMessages()}
  async function loadMessages(){if(!chatUser)return;const r=await db2.from('messages').select('id,sender_id,receiver_id,body,media_url,media_type,created_at').or(`and(sender_id.eq.${window.me.id},receiver_id.eq.${chatUser}),and(sender_id.eq.${chatUser},receiver_id.eq.${window.me.id})`).order('created_at',{ascending:true});if(r.error)return $('messages').innerHTML='<p>'+esc(r.error.message)+'</p>';$('messages').innerHTML=(r.data||[]).map(m=>`<div style="text-align:${m.sender_id===window.me.id?'right':'left'};margin:8px"><span class="pill">${m.media_type==='audio'?`🎙️ <audio controls src="${esc(m.media_url)}"></audio>`:esc(m.body||'')}</span></div>`).join('')||'<p class="muted">Sin mensajes.</p>';$('messages').scrollTop=$('messages').scrollHeight}
  async function sendChat(){if(!chatUser)return;const body=$('chatInput').value.trim();if(!body)return;const r=await db2.from('messages').insert({sender_id:window.me.id,receiver_id:chatUser,body});if(r.error)return alert(r.error.message);$('chatInput').value='';loadMessages()}
  function backChat(){$('chatBox').classList.add('hidden');searchChatUsers()}
  async function toggleVoice(){if(!chatUser)return;if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia)return alert('Tu navegador no permite grabar audio');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});voiceChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)voiceChunks.push(e.data)};recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(voiceChunks,{type:'audio/webm'});const path=`${window.me.id}/voice-${Date.now()}.webm`;const up=await db2.storage.from('media').upload(path,blob,{contentType:'audio/webm'});if(up.error)return alert(up.error.message);const url=db2.storage.from('media').getPublicUrl(path).data.publicUrl;const r=await db2.from('messages').insert({sender_id:window.me.id,receiver_id:chatUser,media_url:url,media_type:'audio'});if(r.error)return alert(r.error.message);$('voiceStatus').textContent='';loadMessages()};recorder.start();$('voiceStatus').textContent='🔴 Grabando... pulsa 🎙️ para detener';}catch(e){alert('No se pudo acceder al micrófono: '+e.message)}}
  function mediaClickHandler(e){const m=e.target.closest('.media');if(!m||e.target.closest('button,input,textarea'))return;const article=m.closest('article');if(!article)return;openMediaModal(m,article)}
  function openMediaModal(m,article){if($('mediaModal'))$('mediaModal').remove();const modal=document.createElement('div');modal.id='mediaModal';modal.style='position:fixed;inset:0;background:rgba(0,0,0,.88);z-index:50;display:flex;align-items:center;justify-content:center;padding:15px';const clone=m.cloneNode(true);clone.style='max-width:95vw;max-height:75vh;object-fit:contain';const id=(article.querySelector('[onclick^="like("]')?.getAttribute('onclick')||'').match(/like\('([^']+)/)?.[1];modal.innerHTML='<div style="background:white;border-radius:16px;padding:15px;max-width:900px;width:100%;max-height:95vh;overflow:auto"><button class="g" style="float:right" onclick="document.getElementById(\'mediaModal\').remove()">✕</button><div id="modalMedia"></div><div class="actions"><button class="g" onclick="like(\''+(id||'')+'\')">❤️ Me gusta</button><button class="g" onclick="shareCurrent(\''+(id||'')+'\')">💬 Compartir al chat</button></div><div id="modalComments"></div><input id="modalComment" placeholder="Escribe un comentario..."><button class="p" onclick="commentCurrent(\''+(id||'')+'\')">Comentar</button></div>';document.body.appendChild(modal);$('modalMedia').appendChild(clone);if(id)loadModalComments(id)}
  async function loadModalComments(id){const r=await db2.from('comments').select('body,created_at,profiles(username)').eq('post_id',id).order('created_at',{ascending:true});if($('modalComments'))$('modalComments').innerHTML=(r.data||[]).map(c=>`<div class="comment"><b>@${esc(c.profiles?.username||'usuario')}</b> ${esc(c.body)}</div>`).join('')||'<p class="muted">Sin comentarios todavía.</p>'}
  async function commentCurrent(id){if(!window.me)return alert('Inicia sesión para comentar');const b=$('modalComment').value.trim();if(!b)return;const r=await db2.from('comments').insert({post_id:id,user_id:window.me.id,body:b});if(r.error)return alert(r.error.message);$('modalComment').value='';loadModalComments(id)}
  async function shareCurrent(id){if(!window.me)return alert('Inicia sesión para compartir');const r=await db2.from('posts').select('media_url,caption').eq('id',id).maybeSingle();if(r.error||!r.data)return alert('Publicación no encontrada');openChat();setTimeout(()=>{const input=prompt('Escribe el usuario al que quieres enviar esta publicación (@usuario):');if(!input)return;db2.from('profiles').select('id').eq('username',input.replace(/^@/,'')).maybeSingle().then(x=>{if(!x.data)return alert('Usuario no encontrado');return db2.from('messages').insert({sender_id:window.me.id,receiver_id:x.data.id,body:'📤 Publicación compartida: '+(r.data.caption||''),media_url:r.data.media_url,media_type:'shared_post'}).then(()=>alert('Enviada al chat'))})},300)}
  window.saveAccent=saveAccent;window.themePanel=themePanel;window.openChat=openChat;window.searchChatUsers=searchChatUsers;window.openConversation=openConversation;window.sendChat=sendChat;window.backChat=backChat;window.toggleVoice=toggleVoice;window.shareCurrent=shareCurrent;window.commentCurrent=commentCurrent;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();