window.DINORAMTIX_CONFIG={supabaseUrl:"https://aaoyqpiydwqobbtdmmno.supabase.co",supabasePublishableKey:"sb_publishable_5SAEn1z1PEtbGe6mNDjcaA_Kfwz-plG"};
(function(){
const db=supabase.createClient(DINORAMTIX_CONFIG.supabaseUrl,DINORAMTIX_CONFIG.supabasePublishableKey),$=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));let chatUser=null,chatName='',poll=null;
async function me(){return (await db.auth.getSession()).data.session?.user||null}async function admin(){let u=await me();if(!u)return false;let r=await db.from('profiles').select('is_admin').eq('id',u.id).maybeSingle();return !!r.data?.is_admin}
function hide(){['feed','explore','reels','create','me','profile','themePanel','adminVerify','chat'].forEach(x=>$(x)?.classList.add('hidden'))}
async function install(){if(!$('app'))return;let tabs=document.querySelector('#app>.tabs');if(tabs&&!$('chatTab')){let b=document.createElement('button');b.id='chatTab';b.className='g';b.textContent='💬 Chat';b.onclick=openChat;tabs.appendChild(b)}if(tabs&&!$('themeTab')){let b=document.createElement('button');b.id='themeTab';b.className='g';b.textContent='🎨 Color';b.onclick=openTheme;tabs.appendChild(b)}if(!$('chat')){let s=document.createElement('section');s.id='chat';s.className='hidden';s.innerHTML=`<div class="card"><div class="row"><button class="g" onclick="chatBack()">←</button><div class="grow"><h2 style="margin:0">💬 Mensajes</h2><div id="chatSubtitle" class="muted">Selecciona un usuario</div></div></div><div id="chatPicker"><input id="chatSearch" placeholder="🔎 Buscar usuario..." oninput="searchChatUsers()"><div id="chatUsers"></div></div><div id="chatConversation" class="hidden"><div class="row"><div class="grow"><b id="chatTitle"></b></div><button class="g" onclick="chatBack()">Cambiar usuario</button></div><div id="messages" style="height:420px;overflow:auto;background:#f5f6f8;border-radius:12px;padding:10px;margin:10px 0"></div><div class="row"><input id="chatInput" placeholder="Escribe un mensaje..." onkeydown="if(event.key==='Enter'){event.preventDefault();sendChat()}"><button class="p" onclick="sendChat()">Enviar</button><button class="g" onclick="toggleVoice()">🎙️</button></div><div id="voiceStatus" class="muted"></div></div></div>`;$('app').appendChild(s)}if(!$('themePanel')){let s=document.createElement('section');s.id='themePanel';s.className='hidden';s.innerHTML='<div class="card"><h2>🎨 Personalizar interfaz</h2><input id="accentPicker" type="color" value="#0095f6" style="width:70px;height:45px"><button class="p" onclick="saveAccent()">Guardar color</button></div>';$('app').appendChild(s)}await loadAccent();await installAdmin();addProfileChat()}
async function openChat(){if(!(await me()))return alert('Inicia sesión para chatear');hide();$('chat').classList.remove('hidden');$('chatPicker').classList.remove('hidden');$('chatConversation').classList.add('hidden');$('chatSubtitle').textContent='Selecciona un usuario';$('chatSearch').value='';searchChatUsers()}
async function searchChatUsers(){let u=await me();if(!u)return;let q=$('chatSearch')?.value.trim()||'',req=db.from('profiles').select('id,username,avatar_url,verified').neq('id',u.id).order('username').limit(50);if(q)req=req.ilike('username','%'+q+'%');let r=await req;if(r.error)return $('chatUsers').innerHTML='<div class="card">'+esc(r.error.message)+'</div>';$('chatUsers').innerHTML=(r.data||[]).map(x=>`<button class="card row" style="width:100%;text-align:left;margin:7px 0" onclick="openConversation('${x.id}','${esc(x.username)}')"><div class="grow"><b>@${esc(x.username)}</b>${x.verified?' 🟦':''}</div><span>💬</span></button>`).join('')||'<p class="muted">No encontramos usuarios.</p>'}
async function openConversation(id,name){chatUser=id;chatName=name;$('chatPicker').classList.add('hidden');$('chatConversation').classList.remove('hidden');$('chatTitle').textContent='@'+name;$('chatSubtitle').textContent='Conversación privada';await loadMessages();clearInterval(poll);poll=setInterval(loadMessages,2500)}
async function loadMessages(){let u=await me();if(!u||!chatUser)return;let r=await db.from('messages').select('id,sender_id,receiver_id,body,media_url,media_type,created_at').or(`and(sender_id.eq.${u.id},receiver_id.eq.${chatUser}),and(sender_id.eq.${chatUser},receiver_id.eq.${u.id})`).order('created_at',{ascending:true}).limit(300);if(r.error)return $('messages').innerHTML='<div class="card">'+esc(r.error.message)+'</div>';$('messages').innerHTML=(r.data||[]).map(m=>{let mine=m.sender_id===u.id,content=m.media_type==='audio'?`🎙️ <audio controls src="${esc(m.media_url||'')}"></audio>`:m.media_type==='shared_post'?`📤 <div>${esc(m.body||'Publicación compartida')}</div>${m.media_url?`<img src="${esc(m.media_url)}" style="max-width:180px;border-radius:10px;margin-top:5px">`:''}`:esc(m.body||'');return `<div style="display:flex;justify-content:${mine?'flex-end':'flex-start'};margin:7px 0"><div style="max-width:78%;padding:10px 13px;border-radius:17px;background:${mine?'#0095f6':'#fff'};color:${mine?'#fff':'#111'}">${content}<div style="font-size:10px;opacity:.6;margin-top:3px">${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</div></div></div>`}).join('')||'<p class="muted" style="text-align:center">Todavía no hay mensajes. 👋</p>';$('messages').scrollTop=$('messages').scrollHeight}
async function sendChat(){let u=await me();if(!u||!chatUser)return;let body=$('chatInput').value.trim();if(!body)return;let r=await db.from('messages').insert({sender_id:u.id,receiver_id:chatUser,body});if(r.error)return alert('No se pudo enviar: '+r.error.message);$('chatInput').value='';loadMessages()}
function chatBack(){clearInterval(poll);$('chatConversation').classList.add('hidden');$('chatPicker').classList.remove('hidden');$('chatSubtitle').textContent='Selecciona un usuario';searchChatUsers()}
async function toggleVoice(){let u=await me();if(!u||!chatUser)return;let rec=window.__dinoRecorder;if(rec?.state==='recording'){rec.stop();return}if(!navigator.mediaDevices?.getUserMedia)return alert('Tu navegador no permite grabar audio');try{let stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks=[],r=new MediaRecorder(stream);window.__dinoRecorder=r;r.ondataavailable=e=>e.data.size&&chunks.push(e.data);r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());let blob=new Blob(chunks,{type:'audio/webm'}),path=`${u.id}/voice-${Date.now()}.webm`,up=await db.storage.from('media').upload(path,blob,{contentType:'audio/webm'});if(up.error)return alert(up.error.message);let url=db.storage.from('media').getPublicUrl(path).data.publicUrl,q=await db.from('messages').insert({sender_id:u.id,receiver_id:chatUser,body:'🎙️ Mensaje de voz',media_url:url,media_type:'audio'});if(q.error)return alert(q.error.message);$('voiceStatus').textContent='';loadMessages()};r.start();$('voiceStatus').textContent='🔴 Grabando... pulsa 🎙️ para detener';}catch(e){alert(e.message)}}
async function openTheme(){hide();$('themePanel').classList.remove('hidden');loadAccent()}async function loadAccent(){let u=await me();if(!u)return;let r=await db.from('user_settings').select('accent').eq('user_id',u.id).maybeSingle();if(r.data?.accent){document.documentElement.style.setProperty('--accent',r.data.accent);if($('accentPicker'))$('accentPicker').value=r.data.accent}if(!$('accentStyle')){let s=document.createElement('style');s.id='accentStyle';s.textContent='.p{background:var(--accent,#0095f6)!important}.mention{color:var(--accent,#0095f6)!important}.verified{background:var(--accent,#168df7)!important}';document.head.appendChild(s)}}async function saveAccent(){let u=await me();if(!u)return alert('Inicia sesión');let c=$('accentPicker').value,r=await db.rpc('set_my_accent',{new_accent:c});if(r.error)return alert(r.error.message);document.documentElement.style.setProperty('--accent',c);alert('Color guardado 🎨')}
async function installAdmin(){if(!(await admin()))return;let tabs=document.querySelector('#app>.tabs');if(tabs&&!$('adminVerifyTab')){let b=document.createElement('button');b.id='adminVerifyTab';b.className='g';b.textContent='🛡️ Verificar usuarios';b.onclick=openAdmin;tabs.appendChild(b)}if(!$('adminVerify')){let s=document.createElement('section');s.id='adminVerify';s.className='hidden';s.innerHTML='<div class="card"><h2>🛡️ Verificar usuarios</h2><p class="muted">Puedes verificar cualquier cuenta.</p><input id="verifySearch" placeholder="Buscar usuario..." oninput="loadVerifyUsers()"><div id="verifyUsers"></div></div>';$('app').appendChild(s)}}async function openAdmin(){hide();$('adminVerify').classList.remove('hidden');loadVerifyUsers()}async function loadVerifyUsers(){let q=$('verifySearch')?.value.trim()||'',req=db.from('profiles').select('id,username,followers_count,verified').order('username').limit(100);if(q)req=req.ilike('username','%'+q+'%');let r=await req;if(r.error)return $('verifyUsers').textContent=r.error.message;$('verifyUsers').innerHTML=(r.data||[]).map(x=>`<div class="card row"><div class="grow"><b>@${esc(x.username)}</b><div class="muted">${x.followers_count||0} seguidores · ${x.verified?'🟦 Verificado':'Sin verificar'}</div></div><button class="${x.verified?'g':'p'}" onclick="setVerified('${x.id}',${!x.verified})">${x.verified?'Quitar':'✓ Verificar'}</button></div>`).join('')}
async function setVerified(id,value){if(!(await admin()))return alert('No autorizado');let r=await db.rpc('admin_set_verified',{target_user:id,new_value:value});if(r.error)return alert(r.error.message);loadVerifyUsers();alert(value?'Usuario verificado 🟦':'Verificado retirado')}
async function addProfileChat(){let box=$('profileBox');if(!box||box.dataset.chatAdded)return;let buttons=box.querySelectorAll('button');let follow=[...buttons].find(b=>/seguir|siguiendo/i.test(b.textContent));if(!follow)return;let id=follow.getAttribute('onclick')?.match(/toggleFollow\('([^']+)'/)?.[1];if(!id)return;let b=document.createElement('button');b.className='g';b.textContent='💬 Chatear';b.onclick=async()=>{let u=await db.from('profiles').select('username').eq('id',id).single();hide();$('chat').classList.remove('hidden');$('chatPicker').classList.add('hidden');$('chatConversation').classList.remove('hidden');chatUser=id;chatName=u.data?.username||'Usuario';$('chatTitle').textContent='@'+chatName;$('chatSubtitle').textContent='Conversación privada';loadMessages()};follow.parentElement?.appendChild(b);box.dataset.chatAdded='1'}
function mentions(t){return esc(t).replace(/(^|\s)@([a-zA-Z0-9_.]{2,30})/g,'$1<span class="mention">@$2</span>')}
window.openChat=openChat;window.searchChatUsers=searchChatUsers;window.openConversation=openConversation;window.sendChat=sendChat;window.chatBack=chatBack;window.toggleVoice=toggleVoice;window.openTheme=openTheme;window.saveAccent=saveAccent;window.loadVerifyUsers=loadVerifyUsers;window.setVerified=setVerified;window.openAdmin=openAdmin;window.mentions=mentions;
let oldStart=window.start;window.start=async function(){let r=oldStart?await oldStart.apply(this,arguments):null;await install();return r};let oldProfile=window.profile;window.profile=async function(id){let r=oldProfile?await oldProfile(id):null;setTimeout(addProfileChat,100);return r};
function boot(){install();new MutationObserver(()=>addProfileChat()).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
(function(){function load(){if(document.getElementById('dinoSocialScript'))return;var s=document.createElement('script');s.id='dinoSocialScript';s.src='./social.js?v=2';s.defer=true;document.head.appendChild(s)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();})();
