/* DinoRamtix Extras V1 — additive features, no backend/schema changes. */
(()=>{
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const KEY='dino_saved_posts_v1';
 const getSaved=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
 const setSaved=a=>localStorage.setItem(KEY,JSON.stringify([...new Set(a)]));
 const toast=(msg)=>{let t=$('#dinoToast');if(!t){t=document.createElement('div');t.id='dinoToast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__dinoToast);window.__dinoToast=setTimeout(()=>t.classList.remove('show'),2200)};
 function styles(){if($('#dinoExtrasStyles'))return;let s=document.createElement('style');s.id='dinoExtrasStyles';s.textContent=`
 #dinoToast{position:fixed;left:50%;bottom:28px;transform:translate(-50%,18px) scale(.96);opacity:0;pointer-events:none;z-index:2147483646;padding:12px 18px;border:1px solid rgba(53,230,255,.25);border-radius:14px;background:rgba(5,10,25,.92);backdrop-filter:blur(16px);box-shadow:0 12px 35px rgba(0,0,0,.4),0 0 25px rgba(53,230,255,.12);color:#eef6ff;font-weight:800;transition:.22s ease}#dinoToast.show{opacity:1;transform:translate(-50%,0) scale(1)}
 .dinoSaveBtn{position:absolute!important;right:12px;bottom:12px;width:38px;height:38px;padding:0!important;border-radius:12px!important;background:rgba(3,7,18,.82)!important;border:1px solid rgba(120,200,255,.2)!important;color:#dceaff!important;backdrop-filter:blur(10px);z-index:4}.dinoSaveBtn.saved{color:#35e6ff!important;border-color:rgba(53,230,255,.45)!important;box-shadow:0 0 18px rgba(53,230,255,.16)}
 .dinoShareBtn{margin-left:6px!important}.dinoSavedPanel{max-width:760px;margin:18px auto}.dinoSavedPanel .savedItem{display:flex;gap:12px;align-items:center;padding:12px;border:1px solid rgba(87,202,255,.12);border-radius:15px;background:rgba(255,255,255,.03);margin:8px 0}.dinoSavedPanel .savedItem .grow{flex:1}.dinoSavedEmpty{text-align:center;padding:30px;color:#8290ad}
 `;document.head.appendChild(s)}
 function postKey(el,i){if(el.dataset.dinoKey)return el.dataset.dinoKey;let media=el.querySelector('img,video');let src=media?.currentSrc||media?.src||'';let txt=(el.innerText||'').slice(0,120);let k='p_'+btoa(unescape(encodeURIComponent(src+'|'+txt+'|'+i))).replace(/[^a-zA-Z0-9]/g,'').slice(0,32);el.dataset.dinoKey=k;return k}
 function decorate(){const candidates=$$('#app .card');let i=0;candidates.forEach(c=>{if(c.id==='chat'||c.id==='adminVerify'||c.id?.startsWith('dino'))return;let media=c.querySelector('img,video');if(!media)return;if(getComputedStyle(c).position==='static')c.style.position='relative';if(!c.querySelector('.dinoSaveBtn')){let k=postKey(c,i++),b=document.createElement('button');b.className='dinoSaveBtn';b.title='Guardar publicación';b.innerHTML='🔖';if(getSaved().includes(k))b.classList.add('saved');b.onclick=e=>{e.stopPropagation();let a=getSaved();if(a.includes(k)){a=a.filter(x=>x!==k);b.classList.remove('saved');toast('Quitado de guardados')}else{a.push(k);b.classList.add('saved');toast('🔖 Publicación guardada')}};c.appendChild(b)}})}
 function addShare(){ $$('button').forEach(b=>{let tx=(b.textContent||'').trim();if(!/^(Compartir|↗|🔗)$/i.test(tx)||b.dataset.dinoShare)return;b.dataset.dinoShare='1';b.classList.add('dinoShareBtn');b.addEventListener('click',async e=>{e.stopPropagation();let c=b.closest('.card')||document.body;let text=(c.innerText||'DinoRamtix').slice(0,180),url=location.href;try{if(navigator.share)await navigator.share({title:'DinoRamtix',text,url});else{await navigator.clipboard.writeText(url);toast('🔗 Enlace copiado')}}catch{}})})}
 function savedPanel(){if($('#dinoSavedPanel'))return;let p=document.createElement('section');p.id='dinoSavedPanel';p.className='card dinoSavedPanel hidden';p.innerHTML='<div class="row"><div class="grow"><h2>🔖 Guardados</h2><div class="muted">Tus publicaciones guardadas en este dispositivo.</div></div><button class="g" id="dinoCloseSaved">Cerrar</button></div><div id="dinoSavedList"></div>';$('app')?.appendChild(p);$('#dinoCloseSaved').onclick=()=>p.classList.add('hidden')}
 function openSaved(){savedPanel();$$('#app>section').forEach(x=>x.classList.add('hidden'));$('#dinoSavedPanel').classList.remove('hidden');let a=getSaved(),list=$('#dinoSavedList');list.innerHTML=a.length?a.map((x,i)=>`<div class="savedItem"><span>🔖</span><div class="grow">Publicación guardada #${i+1}<div class="muted">Guardada en este dispositivo</div></div><button class="g" onclick="dinoRemoveSaved('${x}')">Eliminar</button></div>`).join(''):'<div class="dinoSavedEmpty">Todavía no has guardado publicaciones.</div>'}
 window.dinoRemoveSaved=k=>{setSaved(getSaved().filter(x=>x!==k));openSaved();decorate()};
 function nav(){let tabs=$('#app>.tabs');if(!tabs||$('#dinoSavedTab'))return;let b=document.createElement('button');b.id='dinoSavedTab';b.className='g';b.textContent='🔖 Guardados';b.onclick=openSaved;tabs.appendChild(b)}
 function shortcuts(){if(window.__dinoExtrasKeys)return;window.__dinoExtrasKeys=1;document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='/'||e.key==='s'){let q=$('#dinoGlobalSearch')||$('#chatSearch');if(q){e.preventDefault();q.focus()}}if(e.key==='Escape'){$$('.dinoSavedPanel').forEach(x=>x.classList.add('hidden'))}})}
 function boot(){styles();nav();decorate();addShare();shortcuts();let mo=new MutationObserver(()=>{nav();decorate();addShare()});mo.observe(document.body,{subtree:true,childList:true});}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();

/* DinoRamtix Feed/Intro V2 — visual/additive only; leaves login and existing actions intact. */
(()=>{
 const $=id=>document.getElementById(id);
 const db=()=>window.__dinoDB||window.supabase?.createClient(window.DINORAMTIX_CONFIG.supabaseUrl,window.DINORAMTIX_CONFIG.supabasePublishableKey);
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 function intro(){if($('dinoEntryIntro'))return;const st=document.createElement('style');st.id='dinoEntryIntroCSS';st.textContent=`#dinoEntryIntro{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;background:rgba(2,5,14,.96);backdrop-filter:blur(2px);animation:dinoIntroOut .7s 1.75s forwards;pointer-events:auto}.dinoEntryLogo{font:900 clamp(46px,10vw,96px)/1 Inter,system-ui,sans-serif;letter-spacing:-.07em;background:linear-gradient(100deg,#fff,#35e6ff 45%,#8b5cf6 72%,#ff4fff);-webkit-background-clip:text;color:transparent;opacity:0;transform:translateY(22px) scale(.86);animation:dinoIntroIn .85s .12s cubic-bezier(.16,1,.3,1) forwards;text-shadow:0 0 40px rgba(53,230,255,.2)}.dinoEntrySub{text-align:center;margin-top:14px;color:#86a0c5;font-size:10px;font-weight:900;letter-spacing:.42em;opacity:0;animation:dinoSub .5s .72s forwards}.dinoEntryRing{position:absolute;width:52vmin;height:52vmin;border-radius:50%;border:1px solid rgba(53,230,255,.2);box-shadow:0 0 70px rgba(53,230,255,.08),inset 0 0 70px rgba(139,92,246,.08);animation:dinoRingIn 1.5s cubic-bezier(.16,1,.3,1)}@keyframes dinoIntroIn{to{opacity:1;transform:none}}@keyframes dinoSub{to{opacity:1}}@keyframes dinoRingIn{from{opacity:0;transform:scale(.25) rotate(-25deg)}to{opacity:1;transform:none}}@keyframes dinoIntroOut{to{opacity:0;visibility:hidden;pointer-events:none}}`;
 document.head.appendChild(st);const o=document.createElement('div');o.id='dinoEntryIntro';o.innerHTML='<div class="dinoEntryRing"></div><div><div class="dinoEntryLogo">DinoRamtix 🦖</div><div class="dinoEntrySub">SOCIAL NETWORK</div></div>';document.body.appendChild(o);setTimeout(()=>o.remove(),2500)}
 function dinos(){if($('dinoFloatingDinos'))return;const s=document.createElement('style');s.id='dinoFloatingCSS';s.textContent=`#dinoFloatingDinos{position:fixed;inset:0;pointer-events:none;z-index:0;overflow:hidden}.dinoFloat{position:absolute;opacity:.12;filter:drop-shadow(0 0 8px rgba(53,230,255,.35));animation:dinoFloat 9s ease-in-out infinite}.dinoFloat:nth-child(2n){animation-duration:12s}.dinoFloat:nth-child(3n){animation-duration:15s}@keyframes dinoFloat{0%,100%{transform:translate3d(0,12px,0) rotate(-4deg)}50%{transform:translate3d(25px,-35px,0) rotate(5deg)}}`;
 document.head.appendChild(s);const box=document.createElement('div');box.id='dinoFloatingDinos';for(let i=0;i<15;i++){const e=document.createElement('span');e.className='dinoFloat';e.textContent='🦖';e.style.left=(3+Math.random()*94)+'%';e.style.top=(5+Math.random()*88)+'%';e.style.fontSize=(14+Math.random()*28)+'px';e.style.animationDelay=(-Math.random()*10)+'s';box.appendChild(e)}document.body.appendChild(box)}
 async function verticalFeed(){const host=$('feed');if(!host||host.classList.contains('hidden'))return;let old=$('dinoVerticalFeed');if(old)return;const D=db();if(!D)return;let r=await D.from('posts').select('id,user_id,caption,media_url,media_type,created_at').order('created_at',{ascending:false}).limit(30);if(r.error||!r.data?.length)return;
 const ids=[...new Set(r.data.map(x=>x.user_id).filter(Boolean))];let pr=ids.length?await D.from('profiles').select('id,username,avatar_url,verified').in('id',ids):{data:[]};const pm=new Map((pr.data||[]).map(x=>[x.id,x]));
 let wrap=document.createElement('section');wrap.id='dinoVerticalFeed';wrap.innerHTML='<div class="dinoVFTitle">Para ti · Reels y publicaciones</div><div class="dinoVFScroller"></div><div class="dinoVFArrows"><button id="dinoVFPrev" aria-label="Anterior">↑</button><button id="dinoVFNext" aria-label="Siguiente">↓</button></div>';host.insertBefore(wrap,host.firstChild);
 const sc=wrap.querySelector('.dinoVFScroller');sc.innerHTML=r.data.map((p,i)=>{const u=pm.get(p.user_id)||{};const media=p.media_type==='video'?`<video class="dinoVFMedia" src="${esc(p.media_url)}" muted playsinline loop preload="metadata"></video>`:`<img class="dinoVFMedia" src="${esc(p.media_url)}" loading="lazy">`;return `<article class="dinoVFItem" data-i="${i}">${media}<div class="dinoVFShade"><div><b>@${esc(u.username||'usuario')}${u.verified?' ✓':''}</b><p>${esc(p.caption||'')}</p></div><div class="dinoVFActions"><button onclick="window.dinoVFLike('${p.id}')">❤️</button><button onclick="window.dinoVFComment('${p.id}')">💬</button><button onclick="navigator.share?navigator.share({title:'DinoRamtix',url:location.href}):navigator.clipboard.writeText(location.href)">↗</button></div></div></article>`}).join('');
 const items=[...sc.querySelectorAll('.dinoVFItem')];const go=i=>{i=Math.max(0,Math.min(items.length-1,i));items[i].scrollIntoView({behavior:'smooth',block:'start'})};
 $('dinoVFPrev').onclick=()=>{const i=items.findIndex(x=>x.getBoundingClientRect().top>=-20&&x.getBoundingClientRect().top<window.innerHeight/2);go(i<=0?0:i-1)};$('dinoVFNext').onclick=()=>{const i=items.findIndex(x=>x.getBoundingClientRect().top>=-20&&x.getBoundingClientRect().top<window.innerHeight/2);go(i<0?1:Math.min(items.length-1,i+1))};
 sc.addEventListener('wheel',e=>{if(Math.abs(e.deltaY)<8)return;e.preventDefault();const i=items.findIndex(x=>Math.abs(x.getBoundingClientRect().top-sc.getBoundingClientRect().top)<20);go(i+(e.deltaY>0?1:-1))},{passive:false});
 const io=new IntersectionObserver(es=>es.forEach(e=>{const v=e.target.querySelector('video');if(v){if(e.isIntersecting)e.target.querySelector('video').play().catch(()=>{});else v.pause()}}),{root:sc,threshold:.65});items.forEach(x=>io.observe(x));
 window.dinoVFLike=async id=>{if(window.like)return window.like(id);toast('Inicia sesión para reaccionar')};window.dinoVFComment=id=>{const c=prompt('Escribe un comentario');if(c&&window.comment)window.comment(id,c);else if(c)toast('Usa la publicación para comentar')};
 }
 function feedBoot(){dinos();verticalFeed();const mo=new MutationObserver(()=>verticalFeed());mo.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
 intro();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',feedBoot,{once:true});else feedBoot();
})();