/* DinoRamtix Extras V1 — additive features, no backend/schema changes. */
(()=>{
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const KEY='dino_saved_posts_v1';
 const getSaved=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
 const setSaved=a=>localStorage.setItem(KEY,JSON.stringify([...new Set(a)]));
 const toast=(msg)=>{let t=$('#dinoToast');if(!t){t=document.createElement('div');t.id='dinoToast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__dinoToast);window.__dinoToast=setTimeout(()=>t.classList.remove('show'),2200)};
 function styles(){if($('#dinoExtrasStyles'))return;let s=document.createElement('style');s.id='dinoExtrasStyles';s.textContent=`
 #dinoToast{position:fixed;left:50%;bottom:28px;transform:translate(-50%,18px) scale(.96);opacity:0;pointer-events:none;z-index:2147483646;padding:12px 18px;border:1px solid rgba(53,230,255,.25);border-radius:14px;background:rgba(5,10,25,.92);backdrop-filter:blur(16px);box-shadow:0 12px 35px rgba(0,0,0,.4),0 0 25px rgba(53,230,255,.12);color:#eef6ff;font-weight:800;transition:.22s ease}#dinoToast.show{opacity:1;transform:translate(-50%,0) scale(1)}
 .dinoSaveBtn{position:absolute!important;right:12px;bottom:12px;width:38px;height:38px;padding:0!important;border-radius:12px!important;background:rgba(3,7,18,.82)!important;border:1px solid rgba(120,200,255,.2)!important;color:#dceaff!important;backdrop-filter:blur(10px);z-index:4}.dinoSaveBtn.saved{color:#35e6ff!important;border-color:rgba(53,230,255,.45)!important;box-shadow:0 0 18px rgba(53,230,255,.16)}
 .dinoShareBtn{margin-left:6px!important}.dinoSavedPanel{max-width:760px;margin:18px auto}.dinoSavedPanel .savedItem{display:flex;gap:12px;align-items:center;padding:12px;border:1px solid rgba(87,202,255,.12);border-radius:15px;background:rgba(255,255,255,.03);margin:8px 0}.dinoSavedPanel .savedItem .grow{flex:1}.dinoSavedEmpty{text-align:center;padding:30px;color:#8290ad}
 `;document.head.appendChild(s)}
 function postKey(el,i){if(el.dataset.dinoKey)return el.dataset.dinoKey;let media=el.querySelector('img,video');let src=media?.currentSrc||media?.src||'';let txt=(el.innerText||'').slice(0,120);let k='p_'+btoa(unescape(encodeURIComponent(src+'|'+txt+'|'+i))).replace(/[^a-zA-Z0-9]/g,'').slice(0,32);el.dataset.dinoKey=k;return k}
 function decorate(){const candidates=$$('#app .card');let i=0;candidates.forEach(c=>{if(c.id==='chat'||c.id==='adminVerify'||c.id?.startsWith('dino'))return;let media=c.querySelector('img,video');if(!media)return;if(getComputedStyle(c).position==='static')c.style.position='relative';if(!c.querySelector('.dinoSaveBtn')){let k=postKey(c,i++),b=document.createElement('button');b.className='dinoSaveBtn';b.title='Guardar publicación';b.innerHTML='🔖';if(getSaved().includes(k))b.classList.add('saved');b.onclick=e=>{e.stopPropagation();let a=getSaved();if(a.includes(k)){a=a.filter(x=>x!==k);b.classList.remove('saved');toast('Quitado de guardados')}else{a.push(k);b.classList.add('saved');toast('🔖 Publicación guardada')}};c.appendChild(b)}})}
 function addShare(){ $$('button').forEach(b=>{let tx=(b.textContent||'').trim();if(!/^(Compartir|↗|🔗)$/i.test(tx)||b.dataset.dinoShare)return;b.dataset.dinoShare='1';b.classList.add('dinoShareBtn');b.addEventListener('click',async e=>{e.stopPropagation();let c=b.closest('.card')||document.body;let text=(c.innerText||'DinoRamtix').slice(0,180),url=location.href;try{if(navigator.share)await navigator.share({title:'DinoRamtix',text,url});else{await navigator.clipboard.writeText(url);toast('🔗 Enlace copiado')}}catch{}})})}
 function savedPanel(){if($('#dinoSavedPanel'))return;let p=document.createElement('section');p.id='dinoSavedPanel';p.className='card dinoSavedPanel hidden';p.innerHTML='<div class="row"><div class="grow"><h2>🔖 Guardados</h2><div class="muted">Tus publicaciones guardadas en este dispositivo.</div></div><button class="g" id="dinoCloseSaved">Cerrar</button></div><div id="dinoSavedList"></div>';$('app')?.appendChild(p);$('#dinoCloseSaved').onclick=()=>p.classList.add('hidden')}
 function openSaved(){savedPanel();$$('#app>section').forEach(x=>x.classList.add('hidden'));$('#dinoSavedPanel').classList.remove('hidden');let a=getSaved(),list=$('#dinoSavedList');list.innerHTML=a.length?a.map((x,i)=>`<div class="savedItem"><span>🔖</span><div class="grow">Publicación guardada #${i+1}<div class="muted">Guardada en este dispositivo</div></div><button class="g" onclick="dinoRemoveSaved('${x}')">Eliminar</button></div>`).join(''):'<div class="dinoSavedEmpty">Todavía no has guardado publicaciones.</div>'}
 window.dinoRemoveSaved=k=>{setSaved(getSaved().filter(x=>x!==k));openSaved();decorate()};
 function nav(){let tabs=$('#app>.tabs');if(!tabs||$('#dinoSavedTab'))return;let b=document.createElement('button');b.id='dinoSavedTab';b.className='g';b.textContent='🔖 Guardados';b.onclick=openSaved;tabs.appendChild(b)}
 function shortcuts(){if(window.__dinoExtrasKeys)return;window.__dinoExtrasKeys=1;document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='/'||e.key==='s'){let q=$('#dinoGlobalSearch')||$('#chatSearch');if(q){e.preventDefault();q.focus()}}if(e.key==='Escape'){$$('.dinoSavedPanel').forEach(x=>x.classList.add('hidden'))}})}
 function boot(){styles();nav();decorate();addShare();shortcuts();let mo=new MutationObserver(()=>{nav();decorate();addShare()});mo.observe(document.body,{subtree:true,childList:true});}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
