/* DinoRamtix FUTURE UI — varied mini-games. Visual layer only; existing social logic stays untouched. */
(()=>{
 const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
 const db=window.supabase?.createClient?.(DINORAMTIX_CONFIG.supabaseUrl,DINORAMTIX_CONFIG.supabasePublishableKey);
 const engines=[
  ['🦖','Dino Parkour','2D runner: salta obstáculos y consigue monedas','runner'],['🏃','Neon Runner','Corre, salta y agáchate en una pista 2D','runner'],['🚀','Space Dodge','Mueve la nave y esquiva meteoritos','dodge'],['🐍','Cyber Snake','Come orbes y haz crecer la serpiente','snake'],['🧱','Neon Breakout','Rompe bloques con la pelota','breakout'],['🪜','Tower Jump','Salta entre plataformas y sube','platformer'],['🎯','Target Arena','Apunta a objetivos que aparecen','aim'],['🧠','Memory Grid','Encuentra las parejas','memory'],['⌨️','Word Rush','Escribe palabras antes de que escapen','typing'],['⚡','Reflex Lab','Espera la señal y reacciona','reflex'],['➗','Math Sprint','Resuelve operaciones para avanzar','math'],['🎨','Color Switch','Elige el color correcto','color'],['🏎️','Cyber Kart','Esquiva tráfico en carretera','dodge'],['🪂','Sky Fall','Controla tu caída entre obstáculos','dodge'],['🏹','Dino Archer','Apunta y dispara a dianas','aim'],['💣','Bomb Escape','Encuentra el camino seguro','memory'],['🏓','Paddle Duel','Devuelve la pelota con la paleta','breakout'],['🧊','Ice Climb','Salta plataformas que se mueven','platformer'],['👾','Alien Waves','Muévete y dispara a enemigos','shooter'],['🌌','Galaxy Catch','Mueve la nave para recoger estrellas','catch'],['🧩','Puzzle Shift','Ordena piezas con movimientos','memory'],['🥷','Shadow Dash','Corre por tejados y salta huecos','runner']
 ];
 const prefixes=['Neon','Hyper','Turbo','Quantum','Cyber','Nova','Pixel','Dino','Galaxy','Pulse','Fusion','Cosmic','Ultra','Mega','Vortex','Rocket','Future','Electric','Chrome','Orbit'];
 const catalog=Array.from({length:100000},(_,i)=>{const e=engines[i%engines.length];return{id:i+1,icon:e[0],base:e[1],name:`${prefixes[i%prefixes.length]} ${e[1]} #${i+1}`,desc:e[2],type:e[3],seed:i+1}});
 function styles(){if($('futureStyles'))return;const s=document.createElement('style');s.id='futureStyles';s.textContent=`
 :root{--future-bg:#050816;--future-panel:#0b1222;--future-line:rgba(112,190,255,.16);--future-cyan:#35e6ff;--future-blue:#4c7dff;--future-purple:#8b5cf6;--future-pink:#f04fff;--future-text:#f5f8ff;--future-muted:#8290aa}
 html,body{background:var(--future-bg)!important;color:var(--future-text)!important}body{background:radial-gradient(900px 500px at 15% -10%,rgba(139,92,246,.24),transparent 62%),radial-gradient(800px 520px at 95% 5%,rgba(53,230,255,.16),transparent 60%),linear-gradient(180deg,#060918,#050816 60%,#070b18)!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}body:after{content:"";position:fixed;inset:0;pointer-events:none;z-index:-1;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:32px 32px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.9),transparent 92%)}
 header.card{background:rgba(5,8,22,.78)!important;border-color:var(--future-line)!important;backdrop-filter:blur(20px)!important;box-shadow:0 10px 40px rgba(0,0,0,.3)!important}header b{color:#fff!important;text-shadow:0 0 18px rgba(53,230,255,.32)}.card{background:linear-gradient(145deg,rgba(16,26,48,.92),rgba(7,13,27,.94))!important;border:1px solid var(--future-line)!important;box-shadow:0 18px 55px rgba(0,0,0,.28),inset 0 1px rgba(255,255,255,.035)!important;color:var(--future-text)!important;backdrop-filter:blur(14px)!important}.muted{color:var(--future-muted)!important}.tabs{gap:9px!important}.tabs button{background:rgba(255,255,255,.045)!important;color:#dfe8ff!important;border:1px solid rgba(112,190,255,.12)!important;box-shadow:inset 0 1px rgba(255,255,255,.04),0 6px 20px rgba(0,0,0,.16);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease!important}.tabs button:hover{transform:translateY(-3px)!important;border-color:rgba(53,230,255,.45)!important;box-shadow:0 10px 28px rgba(53,230,255,.12)!important}.tabs .p,.p{background:linear-gradient(135deg,var(--future-purple),var(--future-blue) 52%,var(--future-cyan))!important;color:#fff!important;border:1px solid rgba(255,255,255,.18)!important;box-shadow:0 8px 30px rgba(76,125,255,.25)!important}button{transition:transform .16s ease,filter .16s ease,box-shadow .16s ease!important}button:hover{filter:brightness(1.08)}button:active{transform:scale(.96)}input,textarea,select{background:rgba(255,255,255,.045)!important;color:#fff!important;border:1px solid rgba(112,190,255,.16)!important}.avatar{background:linear-gradient(135deg,var(--future-purple),var(--future-pink),var(--future-cyan))!important}.verified{background:linear-gradient(135deg,#1aa7ff,#65f2ff)!important;box-shadow:0 0 15px rgba(53,230,255,.42)!important}
 .futureModal{position:fixed;inset:0;background:rgba(2,5,14,.82);backdrop-filter:blur(18px);z-index:100000;display:flex;align-items:center;justify-content:center;padding:12px}.futureSheet{width:min(1040px,97vw);max-height:94vh;overflow:auto;border:1px solid rgba(112,190,255,.2);border-radius:26px;padding:20px;background:linear-gradient(145deg,rgba(15,25,47,.98),rgba(5,10,22,.98));box-shadow:0 35px 100px rgba(0,0,0,.6),0 0 80px rgba(76,125,255,.08)}.futureGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.futureGame{min-height:125px;text-align:left;padding:14px;border-radius:17px!important;background:linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.018))!important;border:1px solid rgba(112,190,255,.13)!important;color:#fff!important}.futureGame:hover{transform:translateY(-3px);border-color:rgba(53,230,255,.42)!important;box-shadow:0 12px 30px rgba(53,230,255,.08)}.futureIcon{font-size:28px}.futureGameCount{color:#9caed0;font-size:12px}.futureCanvasWrap{width:min(900px,100%);margin:auto;border:1px solid rgba(112,190,255,.15);border-radius:20px;overflow:hidden;background:#030611;box-shadow:0 20px 60px rgba(0,0,0,.4)}canvas.futureCanvas{display:block;width:100%;height:auto;touch-action:none}.futurePlay{min-height:360px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;border-radius:20px;background:radial-gradient(circle at center,rgba(76,125,255,.12),transparent 55%),rgba(255,255,255,.025);border:1px solid rgba(112,190,255,.12)}.futureScore{font-size:46px;font-weight:900;text-shadow:0 0 25px rgba(53,230,255,.3)}.futureTap{font-size:72px!important;width:150px;height:150px;border-radius:42px!important;background:linear-gradient(145deg,#8b5cf6,#4c7dff,#35e6ff)!important;box-shadow:0 20px 50px rgba(76,125,255,.28)!important}.futureControls{display:flex;gap:10px;justify-content:center;flex-wrap:wrap}.futureControls button{min-width:78px}.futureInstall{animation:futurePulse 2.4s ease-in-out infinite}@keyframes futurePulse{0%,100%{box-shadow:0 0 0 rgba(53,230,255,0)}50%{box-shadow:0 0 28px rgba(53,230,255,.16)}}
 @media(max-width:700px){.futureGrid{grid-template-columns:repeat(2,1fr)}.futureSheet{padding:13px;border-radius:20px}.futureTap{width:125px;height:125px;font-size:58px!important}.futureScore{font-size:38px}}
 `;document.head.appendChild(s)}
 function removeColor(){['themeTab','themePanel'].forEach(id=>$(id)?.remove());document.querySelectorAll('#app>.tabs button').forEach(b=>{if(/🎨\s*Color/i.test(b.textContent||''))b.remove()})}
 async function getUser(){return db?(await db.auth.getSession()).data.session?.user:null}
 async function reward(game,score){const u=await getUser();if(!u){alert('Inicia sesión para guardar monedas.');return false}let r=await db.rpc('add_game_coins',{p_game:game.name.slice(0,80),p_score:Math.max(0,Math.floor(score))});if(r.error){alert(r.error.message);return false}let earned=Number(r.data??Math.floor(score));alert(`🎉 +${earned.toLocaleString('es-CO')} 🪙 monedas`);window.refreshDinoCoins?.();return true}
 function modal(id,html){let m=$(id);if(!m){m=document.createElement('div');m.id=id;m.className='futureModal';document.body.appendChild(m)}m.innerHTML=`<div class="futureSheet">${html}</div>`;m.classList.remove('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')}}
 function openCatalog(){modal('futureGames',`<div class="row"><div class="grow"><h2 style="margin:0">🎮 MiniJuegos FUTURE</h2><p class="muted">100.000 juegos · no todos son de tocar · parkour 2D, carreras, puzzles, disparos y más.</p></div><button class="g" onclick="document.getElementById('futureGames').classList.add('hidden')">✕</button></div><div class="row"><input class="futureSearch grow" id="futureSearch" placeholder="🔎 Buscar juego..." oninput="window.filterFutureGames()"><span class="pill">100K juegos</span></div><div id="futureGrid" class="futureGrid"></div>`);renderCatalog(catalog.slice(0,48))}
 function renderCatalog(list){const b=$('futureGrid');if(!b)return;b.innerHTML=list.map(g=>`<button class="futureGame" onclick="window.playFutureGame(${g.id})"><div class="futureIcon">${g.icon}</div><b>${esc(g.name)}</b><div class="futureGameCount">${esc(g.desc)}</div></button>`).join('')}
 function filter(){let q=($('futureSearch')?.value||'').toLowerCase().trim();renderCatalog((q?catalog.filter(g=>(g.name+' '+g.desc).toLowerCase().includes(q)):catalog).slice(0,80))}
 function gameShell(g,extra){modal('futureGamePlay',`<div class="row"><button class="g" onclick="window.closeFutureGame()">← Juegos</button><div class="grow"><h2 style="margin:0">${g.icon} ${esc(g.name)}</h2></div><b id="futureTopScore">0 pts</b></div>${extra}`)}
 function updateScore(n){if($('futureScore'))$('futureScore').textContent=Math.floor(n);if($('futureTopScore'))$('futureTopScore').textContent=Math.floor(n)+' pts'}
 function tapGame(g){let score=0,active=true;gameShell(g,`<div class="futurePlay"><div class="futureScore" id="futureScore">0</div><button class="futureTap" id="futureTap">${g.icon}</button><p class="muted">Modo rápido. Pulsa cuando quieras.</p><button class="p" id="futureFinish">Terminar y cobrar 🪙</button></div>`);$('futureTap').onclick=()=>{if(active){score++;updateScore(score)}};$('futureFinish').onclick=async()=>{if(!active)return;active=false;await reward(g,score);$('futureGamePlay')?.classList.add('hidden')}}
 function canvasGame(g,type){let score=0,active=true,raf=0,keys={},canvas;gameShell(g,`<div class="futureCanvasWrap"><canvas id="futureCanvas" class="futureCanvas" width="900" height="500"></canvas></div><div id="futureScore" class="futureScore">0</div><div class="futureControls" id="futureControls"><button class="g" data-k="left">◀</button><button class="g" data-k="jump">⬆️ SALTAR</button><button class="g" data-k="right">▶</button><button class="g" data-k="action">🔥 ACCIÓN</button></div><p class="muted">Teclado: ← → ↑ y espacio. En móvil usa los controles.</p><button class="p" id="futureFinish">Terminar y cobrar 🪙</button>`);canvas=$('futureCanvas');const c=canvas.getContext('2d');const W=900,H=500;let t=0;
  function setup(){keys={};for(const b of $('futureControls').querySelectorAll('button'))b.onpointerdown=()=>keys[b.dataset.k]=true,b.onpointerup=()=>keys[b.dataset.k]=false,b.onpointerleave=()=>keys[b.dataset.k]=false;onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp',' '].includes(e.key))e.preventDefault();keys[e.key==='ArrowLeft'?'left':e.key==='ArrowRight'?'right':e.key==='ArrowUp'||e.key===' '?'jump':e.key]=true};onkeyup=e=>{keys[e.key==='ArrowLeft'?'left':e.key==='ArrowRight'?'right':e.key==='ArrowUp'||e.key===' '?'jump':e.key]=false}}
  function drawBase(){c.clearRect(0,0,W,H);c.fillStyle='#030611';c.fillRect(0,0,W,H);for(let x=0;x<W;x+=45){c.strokeStyle='rgba(53,230,255,.055)';c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke()}for(let y=0;y<H;y+=45){c.strokeStyle='rgba(139,92,246,.045)';c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke()}}
  let player={x:110,y:390,w:34,h:48,vy:0,on:true},objs=[],coins=[];
  function runner(){drawBase();c.fillStyle='#182742';c.fillRect(0,438,W,62);player.vy+=.85;player.y+=player.vy;if(player.y+player.h>=438){player.y=390;player.vy=0;player.on=true}if(keys.left)player.x-=5;if(keys.right)player.x+=5;if((keys.jump||keys[' '])&&player.on){player.vy=-15;player.on=false}player.x=Math.max(10,Math.min(W-45,player.x));if(t%65===0)objs.push({x:W+20,y:400,w:25+Math.random()*25,h:38});objs.forEach(o=>o.x-=7);objs=objs.filter(o=>o.x>-60);for(const o of objs){c.fillStyle='#f04fff';c.fillRect(o.x,o.y,o.w,o.h);if(player.x<o.x+o.w&&player.x+player.w>o.x&&player.y+player.h>o.y){score=Math.max(0,score-10);o.x=-100}}if(t%42===0)coins.push({x:W+20,y:300+Math.random()*90});coins.forEach(o=>o.x-=7);coins=coins.filter(o=>o.x>-30);for(const o of coins){c.fillStyle='#ffe45c';c.beginPath();c.arc(o.x,o.y,10,0,7);c.fill();if(Math.hypot(player.x+17-o.x,player.y+24-o.y)<28){score+=15;o.x=-100}}c.fillStyle='#35e6ff';c.fillRect(player.x,player.y,player.w,player.h);c.fillStyle='#fff';c.fillText('SALTA LOS OBSTÁCULOS',25,35)}
  let ship={x:430,y:410},rocks=[];
  function dodge(){drawBase();ship.x+=(keys.left?-8:0)+(keys.right?8:0);ship.y+=(keys.jump?-5:0)+(keys.action?5:0);ship.x=Math.max(20,Math.min(850,ship.x));ship.y=Math.max(30,Math.min(455,ship.y));if(t%22===0)rocks.push({x:Math.random()*870,y:-30,s:18+Math.random()*25,vy:3+Math.random()*4});rocks.forEach(r=>r.y+=r.vy);rocks=rocks.filter(r=>r.y<530);for(const r of rocks){c.fillStyle='#ff527d';c.beginPath();c.arc(r.x,r.y,r.s,0,7);c.fill();if(Math.hypot(ship.x-r.x,ship.y-r.y)<r.s+18){score=Math.max(0,score-20);r.y=600}}score+=.08;c.fillStyle='#35e6ff';c.beginPath();c.moveTo(ship.x,ship.y-24);c.lineTo(ship.x-18,ship.y+20);c.lineTo(ship.x+18,ship.y+20);c.closePath();c.fill();c.fillStyle='#fff';c.fillText('ESQUIVA LOS METEORITOS',25,35)}
  let snake=[{x:450,y:250}],dir={x:1,y:0},food={x:650,y:250};
  function snakeGame(){drawBase();if(t%8===0){let h={x:snake[0].x+dir.x*22,y:snake[0].y+dir.y*22};if(h.x<0||h.x>878||h.y<0||h.y>478){dir={x:0,y:0};active=false}snake.unshift(h);if(Math.hypot(h.x-food.x,h.y-food.y)<22){score+=20;food={x:Math.floor(Math.random()*40)*22,y:Math.floor(Math.random()*22)*22}}else snake.pop()}if(keys.left)dir={x:-1,y:0};if(keys.right)dir={x:1,y:0};if(keys.jump)dir={x:0,y:-1};if(keys.action)dir={x:0,y:1};c.fillStyle='#ffe45c';c.beginPath();c.arc(food.x,food.y,9,0,7);c.fill();snake.forEach((p,i)=>{c.fillStyle=i?'#4c7dff':'#35e6ff';c.fillRect(p.x,p.y,20,20)})}
  let ball={x:450,y:430,vx:5,vy:-5},paddle=380,blocks=[];
  function breakout(){drawBase();if(!blocks.length)for(let y=45;y<150;y+=26)for(let x=35;x<865;x+=58)blocks.push({x,y,w:50,h:18,on:1});paddle+=(keys.left?-9:0)+(keys.right?9:0);paddle=Math.max(0,Math.min(820,paddle));ball.x+=ball.vx;ball.y+=ball.vy;if(ball.x<8||ball.x>892)ball.vx*=-1;if(ball.y<8)ball.vy*=-1;if(ball.y>475){score=Math.max(0,score-10);ball={x:450,y:430,vx:5,vy:-5}}if(ball.y>445&&ball.x>paddle&&ball.x<paddle+80)ball.vy=-Math.abs(ball.vy);for(const b of blocks)if(b.on&&ball.x>b.x&&ball.x<b.x+b.w&&ball.y>b.y&&ball.y<b.y+b.h){b.on=0;ball.vy*=-1;score+=5}blocks.forEach(b=>{if(b.on){c.fillStyle='#8b5cf6';c.fillRect(b.x,b.y,b.w,b.h)}});c.fillStyle='#35e6ff';c.fillRect(paddle,450,80,12);c.fillStyle='#fff';c.beginPath();c.arc(ball.x,ball.y,8,0,7);c.fill()}
  let plats=[{x:360,y:450,w:180,h:18}],py=400,pvy=0,px=440;
  function platformer(){drawBase();if(t%80===0)plats.push({x:Math.random()*760,y:120+Math.random()*280,w:110,h:15});plats=plats.filter(p=>p.y<500);px+=(keys.left?-6:0)+(keys.right?6:0);pvy+=.7;py+=pvy;if(py>450){py=400;pvy=0}if((keys.jump||keys[' '])&&pvy===0)pvy=-13;for(const p of plats){if(px+25>p.x&&px<p.x+p.w&&py+40<=p.y+5&&py+40+pvy>=p.y){py=p.y-40;pvy=0;score+=1}}c.fillStyle='#35e6ff';c.fillRect(px,py,25,40);plats.forEach(p=>{c.fillStyle='#4c7dff';c.fillRect(p.x,p.y,p.w,p.h)});c.fillStyle='#fff';c.fillText('SALTA ENTRE PLATAFORMAS',25,35)}
  function aim(){drawBase();let tx=100+Math.random()*700,ty=90+Math.random()*330;if(t%45===0)aim.target={x:tx,y:ty,ttl:45};aim.target=aim.target||{x:450,y:250,ttl:45};c.fillStyle='#f04fff';c.beginPath();c.arc(aim.target.x,aim.target.y,28,0,7);c.fill();c.strokeStyle='#fff';c.stroke();c.fillStyle='#fff';c.fillText('TOCA EL OBJETIVO',25,35);canvas.onclick=e=>{let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;if(Math.hypot(x-aim.target.x,y-aim.target.y)<35){score+=10;aim.target={x:60+Math.random()*780,y:70+Math.random()*360,ttl:45}}}}
  let current=0;
  function loop(){if(!active)return;t++;if(type==='runner')runner();else if(type==='dodge')dodge();else if(type==='snake')snakeGame();else if(type==='breakout')breakout();else if(type==='platformer')platformer();else if(type==='aim')aim();updateScore(score);raf=requestAnimationFrame(loop)}setup();loop();$('futureFinish').onclick=async()=>{if(!active)return;active=false;cancelAnimationFrame(raf);await reward(g,score);$('futureGamePlay')?.classList.add('hidden')};window.closeFutureGame=()=>{active=false;cancelAnimationFrame(raf);$('futureGamePlay')?.classList.add('hidden')}
 }
 function reflex(g){let active=true,score=0,ready=false,start=0;gameShell(g,`<div class="futurePlay"><div id="reflexText" class="futureScore">ESPERA...</div><button class="futureTap" id="reflexBtn">◉</button><p class="muted">Cuando cambie a verde, pulsa lo más rápido posible.</p><button class="p" id="futureFinish">Terminar y cobrar 🪙</button></div>`);const b=$('reflexBtn'),tx=$('reflexText');let delay=1000+Math.random()*2500;setTimeout(()=>{if(active){ready=true;start=performance.now();tx.textContent='¡AHORA!';b.textContent='⚡'}},delay);b.onclick=()=>{if(!active)return;if(!ready){score=1;tx.textContent='Demasiado pronto 😅';return}score=Math.max(1,Math.round(1000-(performance.now()-start)));tx.textContent=score+' puntos';ready=false};$('futureFinish').onclick=async()=>{active=false;await reward(g,score);$('futureGamePlay')?.classList.add('hidden')};window.closeFutureGame=()=>{active=false;$('futureGamePlay')?.classList.add('hidden')}}
 function mathGame(g){let active=true,score=0,n=0;function q(){let a=2+Math.floor(Math.random()*20),b=2+Math.floor(Math.random()*20),op=Math.random()>.5?'+':'-',ans=op==='+'?a+b:a-b;n++;return{txt:`${a} ${op} ${b} = ?`,ans}}let cur=q();gameShell(g,`<div class="futurePlay"><div id="mathQ" class="futureScore">${cur.txt}</div><input id="mathA" inputmode="numeric" placeholder="Respuesta"><button class="p" id="mathGo">Comprobar</button><div id="futureScore" class="futureScore">0</div><button class="g" id="futureFinish">Terminar y cobrar 🪙</button></div>`);$('mathGo').onclick=()=>{if(Number($('mathA').value)===cur.ans)score+=10;else score=Math.max(0,score-2);$('mathA').value='';cur=q();$('mathQ').textContent=cur.txt;updateScore(score)};$('futureFinish').onclick=async()=>{active=false;await reward(g,score);$('futureGamePlay')?.classList.add('hidden')};window.closeFutureGame=()=>{active=false;$('futureGamePlay')?.classList.add('hidden')}}
 function play(id){const g=catalog[id-1];if(!g)return;if(g.type==='runner'||g.type==='dodge'||g.type==='snake'||g.type==='breakout'||g.type==='platformer'||g.type==='aim'||g.type==='catch'||g.type==='shooter')return canvasGame(g,g.type==='catch'||g.type==='shooter'?'dodge':g.type);if(g.type==='reflex')return reflex(g);if(g.type==='math')return mathGame(g);tapGame(g)}
 function addButton(){const tabs=document.querySelector('#app>.tabs');if(!tabs)return;removeColor();if(!$('futureGamesTab')){let b=document.createElement('button');b.id='futureGamesTab';b.className='g futureInstall';b.textContent='🎮 MiniJuegos+';b.onclick=openCatalog;tabs.appendChild(b)}}
 function boot(){styles();removeColor();addButton();setInterval(()=>{removeColor();addButton()},1500)}
 window.openFutureGames=openCatalog;window.filterFutureGames=filter;window.playFutureGame=play;boot();
})();
