/* DinoRamtix FUTURE UI — visual upgrade + expanded mini-games. Does not replace app logic. */
(()=>{
 const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
 const db=window.supabase?.createClient?.(DINORAMTIX_CONFIG.supabaseUrl,DINORAMTIX_CONFIG.supabasePublishableKey);
 const mechanics=[['🦖','Dino Tap','Toca para sumar puntos','tap'],['🎯','Target Rush','Pulsa objetivos','tap'],['⚡','Neon Reflex','Toca para ganar','tap'],['🧠','Math Burst','Resuelve operaciones','math'],['🔢','Number Dash','Suma puntos','tap'],['🌈','Color Pulse','Elige y gana','tap'],['🚀','Space Tap','Impulsa la nave','tap'],['🍕','Pizza Click','Atrapa porciones','tap'],['💎','Crystal Rush','Consigue cristales','tap'],['🤖','Robot Tap','Activa el robot','tap'],['⭐','Star Hunter','Atrapa estrellas','tap'],['🌋','Volcano Run','Supera el reto','tap']];
 const prefixes=['Neon','Hyper','Turbo','Quantum','Cyber','Nova','Pixel','Dino','Galaxy','Pulse','Fusion','Cosmic','Ultra','Mega','Vortex','Rocket','Future','Electric','Chrome','Orbit'];
 const catalog=Array.from({length:100000},(_,i)=>{const m=mechanics[i%mechanics.length];return{id:i+1,icon:m[0],name:`${prefixes[i%prefixes.length]} ${m[1]} #${i+1}`,desc:m[2],type:m[3],seed:i+1}});
 function styles(){if($('futureStyles'))return;const s=document.createElement('style');s.id='futureStyles';s.textContent=`
 :root{--future-bg:#050816;--future-panel:#0b1222;--future-panel2:#101a30;--future-line:rgba(112,190,255,.16);--future-cyan:#35e6ff;--future-blue:#4c7dff;--future-purple:#8b5cf6;--future-pink:#f04fff;--future-text:#f5f8ff;--future-muted:#8290aa}
 html,body{background:var(--future-bg)!important;color:var(--future-text)!important}body{background:radial-gradient(900px 500px at 15% -10%,rgba(139,92,246,.24),transparent 62%),radial-gradient(800px 520px at 95% 5%,rgba(53,230,255,.16),transparent 60%),linear-gradient(180deg,#060918,#050816 60%,#070b18)!important;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}body:after{content:"";position:fixed;inset:0;pointer-events:none;z-index:-1;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:32px 32px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.9),transparent 92%)}
 header.card{background:rgba(5,8,22,.78)!important;border-color:var(--future-line)!important;backdrop-filter:blur(20px)!important;box-shadow:0 10px 40px rgba(0,0,0,.3)!important}header b{color:#fff!important;text-shadow:0 0 18px rgba(53,230,255,.32)}
 .card{background:linear-gradient(145deg,rgba(16,26,48,.92),rgba(7,13,27,.94))!important;border:1px solid var(--future-line)!important;box-shadow:0 18px 55px rgba(0,0,0,.28),inset 0 1px rgba(255,255,255,.035)!important;color:var(--future-text)!important;backdrop-filter:blur(14px)!important} .muted{color:var(--future-muted)!important}
 .tabs{gap:9px!important}.tabs button{background:rgba(255,255,255,.045)!important;color:#dfe8ff!important;border:1px solid rgba(112,190,255,.12)!important;box-shadow:inset 0 1px rgba(255,255,255,.04),0 6px 20px rgba(0,0,0,.16);transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease,background .18s ease!important}.tabs button:hover{transform:translateY(-3px)!important;border-color:rgba(53,230,255,.45)!important;box-shadow:0 10px 28px rgba(53,230,255,.12),inset 0 1px rgba(255,255,255,.08)!important}.tabs button:active{transform:translateY(0) scale(.97)!important}.tabs .p,.p{background:linear-gradient(135deg,var(--future-purple),var(--future-blue) 52%,var(--future-cyan))!important;color:#fff!important;border:1px solid rgba(255,255,255,.18)!important;box-shadow:0 8px 30px rgba(76,125,255,.25)!important}
 button{transition:transform .16s ease,filter .16s ease,box-shadow .16s ease!important}button:hover{filter:brightness(1.08)}button:active{transform:scale(.96)}input,textarea,select{background:rgba(255,255,255,.045)!important;color:#fff!important;border:1px solid rgba(112,190,255,.16)!important}input:focus,textarea:focus,select:focus{border-color:rgba(53,230,255,.65)!important;box-shadow:0 0 0 4px rgba(53,230,255,.08),0 0 25px rgba(53,230,255,.08)!important}
 .avatar{background:linear-gradient(135deg,var(--future-purple),var(--future-pink),var(--future-cyan))!important;box-shadow:0 0 0 3px rgba(53,230,255,.08),0 8px 25px rgba(0,0,0,.35)}.verified{background:linear-gradient(135deg,#1aa7ff,#65f2ff)!important;box-shadow:0 0 15px rgba(53,230,255,.42)!important}.storyRing{background:linear-gradient(135deg,var(--future-cyan),var(--future-purple),var(--future-pink))!important}
 #auth{background:radial-gradient(circle at 80% 0%,rgba(76,125,255,.17),transparent 35%),linear-gradient(145deg,rgba(15,25,48,.98),rgba(5,10,22,.98))!important;border-color:rgba(76,125,255,.28)!important;box-shadow:0 30px 100px rgba(0,0,0,.55),0 0 80px rgba(76,125,255,.08)!important}#auth h1{color:#fff!important;text-shadow:0 0 30px rgba(53,230,255,.18)}
 .media,.preview{border:1px solid rgba(112,190,255,.1);box-shadow:0 15px 45px rgba(0,0,0,.25)}
 .futureModal{position:fixed;inset:0;background:rgba(2,5,14,.78);backdrop-filter:blur(18px);z-index:100000;display:flex;align-items:center;justify-content:center;padding:12px}.futureSheet{width:min(980px,96vw);max-height:92vh;overflow:auto;border:1px solid rgba(112,190,255,.2);border-radius:26px;padding:20px;background:linear-gradient(145deg,rgba(15,25,47,.98),rgba(5,10,22,.98));box-shadow:0 35px 100px rgba(0,0,0,.6),0 0 80px rgba(76,125,255,.08)}.futureGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.futureGame{min-height:110px;text-align:left;padding:14px;border-radius:17px!important;background:linear-gradient(145deg,rgba(255,255,255,.055),rgba(255,255,255,.018))!important;border:1px solid rgba(112,190,255,.13)!important;color:#fff!important}.futureGame:hover{transform:translateY(-3px);border-color:rgba(53,230,255,.42)!important;box-shadow:0 12px 30px rgba(53,230,255,.08)}.futureIcon{font-size:28px}.futureGameCount{color:#9caed0;font-size:12px}.futurePlay{min-height:350px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:16px;border-radius:20px;background:radial-gradient(circle at center,rgba(76,125,255,.12),transparent 55%),rgba(255,255,255,.025);border:1px solid rgba(112,190,255,.12)}.futureScore{font-size:54px;font-weight:900;text-shadow:0 0 25px rgba(53,230,255,.3)}.futureTap{font-size:72px!important;width:150px;height:150px;border-radius:42px!important;background:linear-gradient(145deg,#8b5cf6,#4c7dff,#35e6ff)!important;box-shadow:0 20px 50px rgba(76,125,255,.28)!important}.futureTap:hover{transform:translateY(-5px) scale(1.03)!important}.futureCoins{font-weight:900;color:#8ff7ff}.futureSearch{margin:12px 0}.futureInstall{animation:futurePulse 2.4s ease-in-out infinite}@keyframes futurePulse{0%,100%{box-shadow:0 0 0 rgba(53,230,255,0)}50%{box-shadow:0 0 28px rgba(53,230,255,.16)}}
 @media(max-width:700px){.futureGrid{grid-template-columns:repeat(2,1fr)}.futureSheet{padding:13px;border-radius:20px}.tabs{padding-bottom:75px!important}.futureTap{width:125px;height:125px;font-size:58px!important}}
 `;document.head.appendChild(s)}
 function removeColor(){['themeTab','themePanel'].forEach(id=>$(id)?.remove());document.querySelectorAll('#app>.tabs button').forEach(b=>{if(/🎨\s*Color/i.test(b.textContent||''))b.remove()})}
 async function getUser(){return db?(await db.auth.getSession()).data.session?.user:null}
 function modal(id,html){let m=$(id);if(!m){m=document.createElement('div');m.id=id;m.className='futureModal';document.body.appendChild(m)}m.innerHTML=`<div class="futureSheet">${html}</div>`;m.classList.remove('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')}}
 function openCatalog(){modal('futureGames',`<div class="row"><div class="grow"><h2 style="margin:0">🎮 MiniJuegos FUTURE</h2><p class="muted">100.000 variantes · sin límite de tiempo · juega y cobra monedas.</p></div><button class="g" onclick="document.getElementById('futureGames').classList.add('hidden')">✕</button></div><div class="row"><input class="futureSearch grow" id="futureSearch" placeholder="🔎 Buscar entre 100.000 juegos..." oninput="window.filterFutureGames()"><span class="pill">100K juegos</span></div><div id="futureGrid" class="futureGrid"></div>`);renderCatalog(catalog.slice(0,48))}
 function renderCatalog(list){const b=$('futureGrid');if(!b)return;b.innerHTML=list.map(g=>`<button class="futureGame" onclick="window.playFutureGame(${g.id})"><div class="futureIcon">${g.icon}</div><b>${esc(g.name)}</b><div class="futureGameCount">${esc(g.desc)}</div></button>`).join('')}
 function filter(){let q=($('futureSearch')?.value||'').toLowerCase().trim();renderCatalog((q?catalog.filter(g=>(g.name+' '+g.desc).toLowerCase().includes(q)):catalog).slice(0,80))}
 function play(id){const g=catalog[id-1];if(!g)return;let score=0,active=true;modal('futureGamePlay',`<div class="row"><button class="g" onclick="window.closeFutureGame()">← Juegos</button><div class="grow"><h2 style="margin:0">${g.icon} ${esc(g.name)}</h2></div><b id="futureTopScore">0 puntos</b></div><div class="futurePlay"><div class="futureScore" id="futureScore">0</div><button class="futureTap" id="futureTap">${g.icon}</button><p class="muted">Sin temporizador. Juega hasta que quieras.</p><button class="p" id="futureFinish">Terminar y cobrar 🪙</button></div>`);const set=n=>{score=n;$('futureScore').textContent=n;$('futureTopScore').textContent=n+' puntos'};$('futureTap').onclick=()=>{if(active)set(score+1)};$('futureFinish').onclick=async()=>{if(!active)return;active=false;const u=await getUser();if(!u)return alert('Inicia sesión para guardar monedas.');let r=await db.rpc('add_game_coins',{p_game:g.name.slice(0,80),p_score:score});if(r.error)return alert(r.error.message);let earned=Number(r.data??score);alert(`🎉 +${earned.toLocaleString('es-CO')} 🪙 monedas`);$('futureGamePlay').classList.add('hidden');window.refreshDinoCoins?.()};window.closeFutureGame=()=>{active=false;$('futureGamePlay')?.classList.add('hidden')}}
 function addButton(){const tabs=document.querySelector('#app>.tabs');if(!tabs)return;removeColor();if(!$('futureGamesTab')){let b=document.createElement('button');b.id='futureGamesTab';b.className='g futureInstall';b.textContent='🎮 MiniJuegos+';b.onclick=openCatalog;tabs.appendChild(b)}}
 function boot(){styles();removeColor();addButton();setInterval(()=>{removeColor();addButton()},1500)}
 window.openFutureGames=openCatalog;window.filterFutureGames=filter;window.playFutureGame=play;boot();
})();
