(function(){
const DB=window.supabase?.createClient?.(DINORAMTIX_CONFIG.supabaseUrl,DINORAMTIX_CONFIG.supabasePublishableKey); if(!DB)return;
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let currentUser=null, modalPost=null, modalReel=null, modalStory=null;
async function sessionUser(){return (await DB.auth.getSession()).data.session?.user||null}
function mediaHtml(url,type,cls='socialMedia'){return type==='video'?`<video class="${cls}" src="${esc(url)}" controls playsinline></video>`:`<img class="${cls}" src="${esc(url)}" loading="lazy">`}
function inject(){if($('socialStyle'))return;let st=document.createElement('style');st.id='socialStyle';st.textContent=`.socialMedia{width:100%;max-height:78vh;object-fit:contain;background:#000;border-radius:12px;display:block;cursor:pointer}.socialModal{position:fixed;inset:0;background:rgba(0,0,0,.9);z-index:100;display:flex;align-items:center;justify-content:center;padding:14px}.socialSheet{width:min(900px,96vw);max-height:94vh;overflow:auto;background:#fff;border-radius:18px;padding:14px}.socialModal .socialMedia{max-height:70vh;cursor:default}.socialActions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.socialComments{max-height:230px;overflow:auto;border-top:1px solid #eee}.socialComment{padding:8px 0;border-bottom:1px solid #eee}.socialClose{float:right}.storyReact{font-size:22px;padding:8px 12px}.reelCard video{width:100%;max-height:720px;object-fit:contain;background:#000;border-radius:12px;cursor:pointer}.reelCard{max-width:680px;margin:12px auto}.socialGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.socialPicker button{width:100%;text-align:left}.socialPicker{display:grid;gap:7px;max-height:260px;overflow:auto}@media(max-width:600px){.socialSheet{padding:10px}.socialGrid{grid-template-columns:1fr}}`;document.head.appendChild(st);let m=document.createElement('div');m.id='socialModal';m.className='socialModal hidden';m.innerHTML='<div id="socialSheet" class="socialSheet"></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)closeSocial()})}
function closeSocial(){$('socialModal')?.classList.add('hidden');modalPost=modalReel=modalStory=null}
function openSocial(title,html){inject();$('socialSheet').innerHTML=`<button class="g socialClose" onclick="closeSocial()">✕</button><h2 style="margin-top:4px">${title}</h2>${html}`;$('socialModal').classList.remove('hidden')}
async function postCounts(id){let l=await DB.from('likes').select('*',{count:'exact',head:true}).eq('post_id',id);let c=await DB.from('comments').select('*',{count:'exact',head:true}).eq('post_id',id);let u=await sessionUser();let mine=false;if(u){let q=await DB.from('likes').select('post_id').eq('post_id',id).eq('user_id',u.id).maybeSingle();mine=!!q.data}return {likes:l.count||0,comments:c.count||0,mine}}
async function reelCounts(id){let l=await DB.from('reel_likes').select('*',{count:'exact',head:true}).eq('reel_id',id);let c=await DB.from('reel_comments').select('*',{count:'exact',head:true}).eq('reel_id',id);let u=await sessionUser();let mine=false;if(u){let q=await DB.from('reel_likes').select('reel_id').eq('reel_id',id).eq('user_id',u.id).maybeSingle();mine=!!q.data}return {likes:l.count||0,comments:c.count||0,mine}}
async function commentsForPost(id){let r=await DB.from('comments').select('id,body,created_at,profiles(username,avatar_url,verified)').eq('post_id',id).order('created_at',{ascending:true}).limit(100);return r.data||[]}
async function commentsForReel(id){let r=await DB.from('reel_comments').select('id,body,created_at,profiles(username,avatar_url,verified)').eq('reel_id',id).order('created_at',{ascending:true}).limit(100);return r.data||[]}
function commentList(cs){return cs.length?cs.map(c=>`<div class="socialComment"><b>@${esc(c.profiles?.username||'Usuario')}</b>${c.profiles?.verified?' 🟦':''} ${esc(c.body)}<div class="muted small">${new Date(c.created_at).toLocaleString()}</div></div>`).join(''):'<p class="muted">Todavía no hay comentarios.</p>'}
async function togglePostLike(id){let u=await sessionUser();if(!u)return alert('Inicia sesión para dar me gusta.');let q=await DB.from('likes').select('post_id').eq('post_id',id).eq('user_id',u.id).maybeSingle();let r=q.data?await DB.from('likes').delete().eq('post_id',id).eq('user_id',u.id):await DB.from('likes').insert({post_id:id,user_id:u.id});if(r.error)return alert(r.error.message);await renderPostModal(id)}
async function toggleReelLike(id){let u=await sessionUser();if(!u)return alert('Inicia sesión para dar me gusta.');let q=await DB.from('reel_likes').select('reel_id').eq('reel_id',id).eq('user_id',u.id).maybeSingle();let r=q.data?await DB.from('reel_likes').delete().eq('reel_id',id).eq('user_id',u.id):await DB.from('reel_likes').insert({reel_id:id,user_id:u.id});if(r.error)return alert(r.error.message);await renderReelModal(id)}
async function addPostComment(id){let u=await sessionUser();let el=$('socialCommentInput');let body=el?.value.trim();if(!u)return alert('Inicia sesión para comentar.');if(!body)return;let r=await DB.from('comments').insert({post_id:id,user_id:u.id,body});if(r.error)return alert(r.error.message);el.value='';renderPostModal(id)}
async function addReelComment(id){let u=await sessionUser();let el=$('socialCommentInput');let body=el?.value.trim();if(!u)return alert('Inicia sesión para comentar.');if(!body)return;let r=await DB.from('reel_comments').insert({reel_id:id,user_id:u.id,body});if(r.error)return alert(r.error.message);el.value='';renderReelModal(id)}
async function shareToChat(url,type,label){let u=await sessionUser();if(!u)return alert('Inicia sesión para compartir al chat.');let r=await DB.from('profiles').select('id,username,verified').neq('id',u.id).order('username').limit(100);if(r.error)return alert(r.error.message);openSocial('Compartir al chat',`<p class="muted">Selecciona un usuario para enviar esta ${label}.</p><div class="socialPicker">${(r.data||[]).map(x=>`<button class="card row" onclick="sendShared('${x.id}','${esc(x.username)}','${esc(url)}','${type}','${esc(label)}')"><span class="grow">@${esc(x.username)}${x.verified?' 🟦':''}</span>💬</button>`).join('')}</div>`)}
async function sendShared(id,name,url,type,label){let u=await sessionUser();let r=await DB.from('messages').insert({sender_id:u.id,receiver_id:id,body:'📤 '+label+' compartida',media_url:url,media_type:'shared_post'});if(r.error)return alert(r.error.message);closeSocial();alert('Enviado a @'+name+' 💬')}
async function renderPostModal(id){let r=await DB.from('posts').select('id,user_id,caption,media_url,media_type,created_at,profiles(username,avatar_url,verified)').eq('id',id).single();if(r.error)return alert(r.error.message);let p=r.data,c=await postCounts(id),cs=await commentsForPost(id);modalPost=id;openSocial('@'+esc(p.profiles?.username||'Usuario')+(p.profiles?.verified?' 🟦':''),`${mediaHtml(p.media_url,p.media_type)}<p>${esc(p.caption||'')}</p><div class="socialActions"><button class="g" onclick="togglePostLike('${id}')">${c.mine?'💙':'❤️'} ${c.likes} Me gusta</button><button class="g" onclick="document.getElementById('socialCommentInput').focus()">💬 ${c.comments} Comentarios</button><button class="g" onclick="shareToChat('${esc(p.media_url)}','${esc(p.media_type)}','publicación')">📤 Compartir</button></div><div class="row"><input id="socialCommentInput" placeholder="Escribe un comentario..." onkeydown="if(event.key==='Enter'){addPostComment('${id}')}"><button class="p" onclick="addPostComment('${id}')">Enviar</button></div><div class="socialComments">${commentList(cs)}</div>`)}
async function renderReelModal(id){let r=await DB.from('reels').select('id,user_id,caption,video_url,created_at,profiles(username,avatar_url,verified)').eq('id',id).single();if(r.error)return alert(r.error.message);let p=r.data,c=await reelCounts(id),cs=await commentsForReel(id);modalReel=id;openSocial('@'+esc(p.profiles?.username||'Usuario')+(p.profiles?.verified?' 🟦':''),`${mediaHtml(p.video_url,'video')}<p>${esc(p.caption||'')}</p><div class="socialActions"><button class="g" onclick="toggleReelLike('${id}')">${c.mine?'💙':'❤️'} ${c.likes} Me gusta</button><button class="g" onclick="document.getElementById('socialCommentInput').focus()">💬 ${c.comments} Comentarios</button><button class="g" onclick="shareToChat('${esc(p.video_url)}','video','Reel')">📤 Compartir</button></div><div class="row"><input id="socialCommentInput" placeholder="Escribe un comentario..." onkeydown="if(event.key==='Enter'){addReelComment('${id}')}"><button class="p" onclick="addReelComment('${id}')">Enviar</button></div><div class="socialComments">${commentList(cs)}</div>`)}
async function renderReels(){let box=$('reelList');if(!box)return;let r=await DB.from('reels').select('id,user_id,caption,video_url,created_at,profiles(username,avatar_url,verified)').order('created_at',{ascending:false}).limit(50);if(r.error){box.innerHTML='<div class="card">'+esc(r.error.message)+'</div>';return}let html='';for(const x of r.data||[]){let c=await reelCounts(x.id);html+=`<article class="card reelCard"><div class="row"><div class="grow"><b>@${esc(x.profiles?.username||'Usuario')}${x.profiles?.verified?' 🟦':''}</b></div><span class="muted">${new Date(x.created_at).toLocaleDateString()}</span></div><div onclick="renderReelModal('${x.id}')">${mediaHtml(x.video_url,'video')}</div><p>${esc(x.caption||'')}</p><div class="socialActions"><button class="g" onclick="toggleReelLike('${x.id}')">${c.mine?'💙':'❤️'} ${c.likes}</button><button class="g" onclick="renderReelModal('${x.id}')">💬 ${c.comments}</button><button class="g" onclick="shareToChat('${esc(x.video_url)}','video','Reel')">📤 Compartir</button></div></article>`}box.innerHTML=html||'<div class="card">No hay Reels todavía.</div>'}
async function renderStories(){let r=await DB.from('stories').select('id,user_id,media_url,media_type,caption,created_at,expires_at,profiles(username,avatar_url,verified)').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(100);if(r.error||!r.data)return;let by={};r.data.forEach(x=>(by[x.user_id]??=[]).push(x));let bar=$('stories');if(!bar)return;let html='<b>Stories</b><div class="storybar">';for(const uid of Object.keys(by)){let s=by[uid][0];html+=`<div class="storyItem" onclick="renderStoryViewer('${uid}')"><div class="storyRing"><div class="avatar">${s.profiles?.avatar_url?`<img src="${esc(s.profiles.avatar_url)}">`:esc((s.profiles?.username||'?')[0].toUpperCase())}</div></div><div>${esc(s.profiles?.username||'Usuario')}${s.profiles?.verified?' 🟦':''}</div></div>`}bar.innerHTML=html+'</div>'}
async function renderStoryViewer(uid){let r=await DB.from('stories').select('id,user_id,media_url,media_type,caption,created_at,expires_at,profiles(username,avatar_url,verified)').eq('user_id',uid).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:true});if(r.error||!r.data?.length)return;let i=0;async function show(){let s=r.data[i],rc=await DB.from('story_reactions').select('reaction').eq('story_id',s.id),mine=await sessionUser();let myReaction=mine?(await DB.from('story_reactions').select('reaction').eq('story_id',s.id).eq('user_id',mine.id).maybeSingle()).data?.reaction:null;let cs=await DB.from('story_comments').select('id,body,created_at,profiles(username,verified)').eq('story_id',s.id).order('created_at',{ascending:true}).limit(100);openSocial('@'+esc(s.profiles?.username||'Usuario')+(s.profiles?.verified?' 🟦':''),`${mediaHtml(s.media_url,s.media_type)}<p>${esc(s.caption||'')}</p><div class="socialActions"><button class="storyReact" onclick="reactStory('${s.id}','❤️')">❤️</button><button class="storyReact" onclick="reactStory('${s.id}','😂')">😂</button><button class="storyReact" onclick="reactStory('${s.id}','🔥')">🔥</button><button class="storyReact" onclick="reactStory('${s.id}','😍')">😍</button><button class="storyReact" onclick="reactStory('${s.id}','👏')">👏</button><span class="muted">${rc.data?.length||0} reacciones ${myReaction?'· Tu reacción: '+myReaction:''}</span><button class="g" onclick="shareToChat('${esc(s.media_url)}','${esc(s.media_type)}','Story')">📤 Compartir</button></div><div class="row"><input id="socialCommentInput" placeholder="Responder a la story..." onkeydown="if(event.key==='Enter'){addStoryComment('${s.id}')}"><button class="p" onclick="addStoryComment('${s.id}')">Enviar</button></div><div class="socialComments">${commentList(cs.data||[])}</div><div class="socialActions"><button class="g" onclick="prevStory()">←</button><span class="grow" style="text-align:center">${i+1}/${r.data.length}</span><button class="g" onclick="nextStory()">→</button></div>`)}window.nextStory=()=>{if(i<r.data.length-1){i++;show()}else closeSocial()};window.prevStory=()=>{if(i>0){i--;show()}};show()}
async function reactStory(storyId,reaction){let u=await sessionUser();if(!u)return alert('Inicia sesión para reaccionar.');let q=await DB.from('story_reactions').select('reaction').eq('story_id',storyId).eq('user_id',u.id).maybeSingle();let r=q.data?await DB.from('story_reactions').update({reaction}).eq('story_id',storyId).eq('user_id',u.id):await DB.from('story_reactions').insert({story_id:storyId,user_id:u.id,reaction});if(r.error)return alert(r.error.message);renderStoryViewer((await DB.from('stories').select('user_id').eq('id',storyId).single()).data.user_id)}
async function addStoryComment(id){let u=await sessionUser(),el=$('socialCommentInput'),body=el?.value.trim();if(!u)return alert('Inicia sesión para comentar.');if(!body)return;let r=await DB.from('story_comments').insert({story_id:id,user_id:u.id,body});if(r.error)return alert(r.error.message);el.value='';let s=await DB.from('stories').select('user_id').eq('id',id).single();renderStoryViewer(s.data.user_id)}
function hook(){inject();let old=window.reels;window.reels=renderReels;let oldStories=window.stories;window.stories=renderStories;window.openStory=renderStoryViewer;document.addEventListener('click',e=>{let m=e.target.closest('.media');if(!m)return;if(e.target.tagName==='VIDEO'&&e.target.controls)return;let art=m.closest('article');let b=art?.querySelector('[onclick*="renderPostModal"]');if(b)return;});}
window.closeSocial=closeSocial;window.renderPostModal=renderPostModal;window.renderReelModal=renderReelModal;window.togglePostLike=togglePostLike;window.toggleReelLike=toggleReelLike;window.addPostComment=addPostComment;window.addReelComment=addReelComment;window.shareToChat=shareToChat;window.sendShared=sendShared;window.renderReels=renderReels;window.renderStories=renderStories;window.renderStoryViewer=renderStoryViewer;window.reactStory=reactStory;window.addStoryComment=addStoryComment;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();
})();
